#!/usr/bin/env node
/**
 * Regenerate every local `.env` from the Doppler config scoped to this
 * directory.
 *
 * Doppler holds the values; each `.env.example` decides which of them a given
 * app is allowed to see. Treating the example file as the manifest means a new
 * variable is declared in exactly one place — the same file that documents it —
 * and no app ends up holding a secret it has no use for.
 *
 * The generated files are not a second source of truth. They exist because
 * `docker compose` reads `env_file:` off disk and cannot be handed an injected
 * environment, and because `pnpm dev` must keep working for anyone without
 * Doppler access. Re-run this after changing anything in Doppler.
 *
 *   pnpm env:pull
 *
 * Prints key names only — never a value.
 */

import { execFileSync } from 'node:child_process';
import { chmodSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

/** Every target that keeps a local `.env`, in the order they are reported. */
const TARGETS = ['apps/api', 'apps/signaling', 'apps/web', 'packages/db'];

const HEADER = `# Generated by \`pnpm env:pull\` from the Doppler config scoped to this
# repository. Do not edit — run \`pnpm env:pull\` again after changing a value
# in Doppler, or edit this file only if you are not using Doppler at all.
#
# Real environment variables always win over this file.
`;

/**
 * Key names an app declares, taken from its `.env.example`.
 *
 * Commented-out entries count: a variable like \`REDIS_URL\` is optional rather
 * than absent, and should be filled in when Doppler happens to carry it.
 */
function declaredKeys(dir) {
  const example = readFileSync(join(ROOT, dir, '.env.example'), 'utf8');
  const keys = new Set();
  for (const line of example.split('\n')) {
    const match = line.match(/^#?\s*([A-Z_][A-Z0-9_]*)=/);
    if (match) keys.add(match[1]);
  }
  return [...keys];
}

/**
 * Render one `KEY=value` line.
 *
 * Quotes only when the value would otherwise be misread — an unquoted `#`
 * starts a comment, and leading or trailing space is silently trimmed. Values
 * that need no quoting do not get any, because `env_file:` and dotenv have
 * historically disagreed about stripping them.
 */
function renderLine(key, value) {
  const safe = /^[^\s#"'`\\\n]*$/.test(value);
  if (safe) return `${key}=${value}`;
  return `${key}="${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

function main() {
  let secrets;
  try {
    const raw = execFileSync('doppler', ['secrets', 'download', '--no-file', '--format', 'json'], {
      cwd: ROOT,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'pipe'],
    });
    secrets = JSON.parse(raw);
  } catch (error) {
    console.error('Could not read secrets from Doppler.');
    console.error('Check `doppler setup --project cougny --config dev` has been run here.');
    console.error(String(error.message ?? error).split('\n')[0]);
    process.exit(1);
  }

  const missingAnywhere = new Set();

  for (const dir of TARGETS) {
    const keys = declaredKeys(dir).sort();
    const written = [];
    const missing = [];

    const body = keys
      .map((key) => {
        // Doppler's own bookkeeping variables are not application config.
        if (key.startsWith('DOPPLER_')) return null;
        const value = secrets[key];
        if (value === undefined) {
          missing.push(key);
          missingAnywhere.add(key);
          return null;
        }
        written.push(key);
        return renderLine(key, value);
      })
      .filter((line) => line !== null)
      .join('\n');

    const path = join(ROOT, dir, '.env');
    writeFileSync(path, `${HEADER}\n${body}\n`, { mode: 0o600 });
    // `mode` above only applies when the file is created, and these are almost
    // always being overwritten. These files hold secrets: narrow them either way.
    chmodSync(path, 0o600);

    console.log(`${dir}/.env — ${written.length} ${written.length === 1 ? 'key' : 'keys'}`);
    if (missing.length > 0) {
      console.log(`  not in Doppler, left out: ${missing.join(', ')}`);
    }
  }

  if (missingAnywhere.size > 0) {
    console.log('');
    console.log('Some declared keys are absent from the Doppler config. That is expected for');
    console.log('optional ones (REDIS_URL, SMTP_URL); anything else is worth a look.');
  }
}

main();
